#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
           - ${ssh_public_key}
package_update: true
package_upgrade: false
packages:
  - vim
  - mc
  - net-tools
  - bind9utils
  - pip
  - python3-netaddr
  - git
  - curl
